name = "Stellar Skies"
author = "W0lverine_14"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4cd9815c500fcbfb28fd58144d44c2c9fd46e71ef6bbf444975fbb6c243e37bf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
