name = "Stellar Skies"
author = "W0lverine_14"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a44a76e60e5a1c3c616fd03d7f80fe194ebeaefc214cbe7a8a5c021bdc96992"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
