name = "Stellar Skies"
author = "W0lverine_14"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf9e33fe3a35e296d6123525a8625e2b8cf04f2d4a8979a5eea5e03188c3f46d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
