[stage]
# =============================================================================
id             = "andesite_age"
display_name   = "Andesite Age"
dependency     = ["stone_age"]
unlock_message = "&6&lAndesite Age Unlocked!"

[locks]
# =============================================================================
items = [
    "create:brass_casing",
    "create:brass_ingot"
]
mods = [
    "create",
    "aeronautics",
    "simulated",
    "offroad"
]
unlocked_items = [
    "create:andesite_alloy"
]
