[stage]
id             = "brass_age"
display_name   = "Brass Age"
dependency     = ["andesite_age"]
unlock_message = "&6&lBrass Age Unlocked!"

[locks]
# =============================================================================
items = [
    #Aeronautics
    "aeronautics:propeller_bearing",
    "aeronautics:gyroscopic_propeller_bearing",
    "aeronautics:smart_propeller",
    #Smulated
    "simulated:gyroscopic_mechanism",
    "simulated:navigation_table",
    "simulated:gimbal_sensor",
    "simulated:optical_sensor",
    "simulated:redstone_inductor",
    "simulated:directional_linked_reciever",
    "simulated:redstone_accumulator",
    "simulated:modulating_linked_receiver",
    "simulated:docking_connector",
    "simulated:analog_transmission",
    "simulated:throttle_lever",
    "simulated:linked_typewriter",
    "simulated:directional_linked_receiver",

    #Create Redstone
    "create:content_observer",
    "create:pulse_repeater",
    "create:pulse_extender",
    "create:pulse_timer",
    "create:stockpile_switch",
    "create:display_link",
    "create:peculiar_bell",
    "create:haunted_bell",
    
    #Create Components
    "create:brass_hand",
    "create:brass_sheet",
    
    #Create Decorations
    "create:brass_table_cloth",
    "create:brass_bars",
    "create:brass_door",
    "create:brass_scaffolding",
    "create:brass_ladder",
    "create:brass_block",

    #Create Contraptions
    "create:elevator_pulley",
    "create:smart_fluid_pipe",
    "create:flywheel",
    "create:rotation_speed_controller",
    "create:mechanical_arm",
    "create:mechanical_crafter",
    "create:sequenced_gearshift",

    #Create Filters
    "create:smart_chute",
    "create:brass_tunnel",
    "create:brass_funnel",
    "create:filter",
    "create:attribute_filter",
    "create:package_filter",

    #Create Tools
    "create:wand_of_symmetry",
    "create:extendo_grip",
    "create:crafter_slot_cover",

    #Create Trains
    "create:track",
    "create:track_observer",
    "create:track_signal",
    "create:track_station",
    "create:railway_casing",
    "create:train_door",
    "create:train_trapdoor",
    "create:schedule",
    "create:controls"
]